<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        $blogs = [
            [
                'id'           => 4,
                'title'        => 'New Chapter',
                'slug'         => 'new-chapter-eM4gy',
                'content'      => '<p>We\'re excited to introduce a new chapter — <strong>Subsidiary Spotlight</strong> — where we highlight the impact and contributions of our subsidiaries. In this edition, we take a closer look at one of our key corporate restructuring milestones: the establishment of <strong>RAYA CONSTRUCTION</strong>.</p><p>Presented in a light yet insightful format, Morning Toolbox offers a fresh perspective on how Azure\'s subsidiaries are shaping the future of the industry.</p><p>Also watch the full video now on our YouTube channel: <strong>Azure Investama Grup</strong>.</p><p><em>Morning Toolbox — because every morning is a new opportunity to grow.</em></p>',
                'image'        => 'blog-images/01JXM3GPTS92GWR2KQCP3VVND1.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-06-13 07:00:23',
                'created_at'   => '2025-06-13 07:00:23',
                'updated_at'   => '2025-06-13 07:00:23',
                'deleted_at'   => null,
            ],
            [
                'id'           => 5,
                'title'        => 'Catalyst Loading',
                'slug'         => 'catalyst-loading-successfully-completed-at-pt-lotte-chemical-indonesia-uYh8N',
                'content'      => '<p>We are proud to announce the <strong>successful completion</strong> of a catalyst and inert ball loading project for the BTX Reactors of the Gasoline Hydrotreating Unit (GHU) I &amp; II, as well as the Clay Tower, at <strong>PT Lotte Chemical Indonesia</strong>.</p><p>This critical project was entrusted to RKI under the main contractor KINE JO. Over the course of <strong>20 days</strong>, our experienced team managed the precise loading of <strong>330 cubic meters</strong> of catalyst across five reactors — a task requiring meticulous planning, safety assurance, and technical execution.</p><p>To ensure the highest performance standards, we deployed highly trained and licensed technicians, state-of-the-art vacuum and hopper systems, and stringent quality assurance and safety protocols.</p>',
                'image'        => 'blog-images/01JY3KJXHW37VNMPP3WCT65DCE.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-06-19 06:00:00',
                'created_at'   => '2025-06-19 06:00:00',
                'updated_at'   => '2025-06-19 06:00:00',
                'deleted_at'   => null,
            ],
            [
                'id'           => 6,
                'title'        => 'Independence Day Celebration',
                'slug'         => 'independence-day-celebration-Pjpj9',
                'content'      => '<p>In commemoration of <strong>Indonesia\'s Independence Day</strong>, RAYA is hosting a series of exciting activities designed not only to spark joy, but also to strengthen the bonds among all team members.</p><p>This moment provides an opportunity for everyone to connect, engage in warm conversations, and build deeper trust — fostering harmony and collaboration in the RAYA workplace.</p><p>With the spirit of freedom and positive energy, synergy and teamwork will pave the way toward achieving greater goals, just as the nation once fought with determination to gain its independence.</p>',
                'image'        => 'blog-images/01K56BFFB1W5KFQDDPWK8CN3ZC.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-08-18 09:32:02',
                'created_at'   => '2025-08-18 09:32:02',
                'updated_at'   => '2025-08-18 09:32:02',
                'deleted_at'   => null,
            ],
            [
                'id'           => 7,
                'title'        => 'New Office',
                'slug'         => 'new-office-7aljR',
                'content'      => '<p>PT Raya Konstruksi Internasional is thrilled to announce our move to a <strong>brand-new office</strong> — a space that marks more than just a change of address. This milestone represents growth, innovation, and our continuous pursuit of excellence.</p><p>This relocation symbolizes a new beginning, igniting a fresh spirit of collaboration, creativity, and commitment within our team. We believe this inspiring environment will foster greater productivity, deeper synergy, and renewed enthusiasm as we continue to deliver the highest quality of service to our valued clients.</p><p><em>Here\'s to new beginnings, stronger partnerships, and a brighter future together!</em></p>',
                'image'        => 'blog-images/01K6WN4NB87NHS124T47T1J2WZ.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-08-13 11:39:47',
                'created_at'   => '2025-08-13 11:39:47',
                'updated_at'   => '2025-08-13 11:39:47',
                'deleted_at'   => null,
            ],
            [
                'id'           => 9,
                'title'        => 'Hari Kesaktian Pancasila',
                'slug'         => 'hari-kesaktian-pancasila-mtI5s',
                'content'      => '<p>Hari Kesaktian Pancasila merupakan momen berharga untuk memperkuat semangat persatuan, kebersamaan, dan rasa cinta tanah air. Dengan menjadikan <strong>Pancasila</strong> sebagai pedoman dalam setiap langkah, kita dapat terus bekerja, berkarya, dan berkontribusi demi Indonesia yang lebih kokoh, berdaulat, dan maju.</p><p>Mari kita bersama-sama menjaga serta mengamalkan nilai-nilai luhur bangsa ini — sebagai fondasi yang menguatkan generasi penerus dan memastikan semangat Pancasila tetap hidup dalam setiap karya dan tindakan kita.</p>',
                'image'        => 'blog-images/01K6WNCQKMD858FEEVYNN0SE7S.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-10-01 11:43:57',
                'created_at'   => '2025-10-01 11:43:57',
                'updated_at'   => '2025-10-01 11:43:57',
                'deleted_at'   => null,
            ],
            [
                'id'           => 10,
                'title'        => 'Tahun Baru Islam 1447',
                'slug'         => 'tahun-baru-islam-1447-MU3de',
                'content'      => '<p>Selamat <strong>Tahun Baru Hijriah 1447 H!</strong> 🌙</p><p>Mari kita sambut tahun baru ini dengan hati yang ikhlas, pikiran yang jernih, dan tekad yang kuat untuk menjadi pribadi yang lebih baik setiap harinya.</p><p>Semoga pergantian tahun ini membawa keberkahan, kedamaian, dan semangat baru bagi kita semua — untuk terus melangkah maju dengan penuh keyakinan, keikhlasan, dan harapan akan masa depan yang lebih baik.</p>',
                'image'        => 'blog-images/01K6WNFDA9567MEP81QBMMAH7B.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-06-27 11:45:49',
                'created_at'   => '2025-06-27 11:45:49',
                'updated_at'   => '2025-06-27 11:45:49',
                'deleted_at'   => null,
            ],
            [
                'id'           => 12,
                'title'        => 'A Day in the Life of Catalyst Loading',
                'slug'         => 'a-day-in-the-life-of-catalyst-loading-JGIKp',
                'content'      => '<p>At Raya Konstruksi, <strong>catalyst loading</strong> is where science meets skilled execution. It\'s a delicate, high-stakes process that keeps industrial plants running safely and efficiently.</p><p>Our methodical approach includes:</p><ul><li>Careful planning and risk assessment</li><li>Safety first — specialized protective gear for every technician</li><li>Precision placement using vacuum and hopper systems</li><li>Real-time quality control checks throughout</li></ul><p>From refineries to chemical plants, our experienced technicians bring reliability and meticulous care to every catalyst loading project, minimizing downtime and maximizing operational integrity.</p>',
                'image'        => 'blog-images/01K80A92879NFN89B3XWY3NHY4.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-02-22 08:00:11',
                'created_at'   => '2025-02-22 08:00:11',
                'updated_at'   => '2025-02-22 08:00:11',
                'deleted_at'   => null,
            ],
            [
                'id'           => 13,
                'title'        => 'Tahun Baru Masehi 2025',
                'slug'         => 'tahun-baru-masehi-2025-OQR3v',
                'content'      => '<p>The New Year is always a symbol of new beginnings — a perfect time to evaluate, improve, and enhance performance. For <strong>Rayakonstruksi</strong>, the start of a new year is the ideal moment to conduct comprehensive <strong>plant maintenance</strong>.</p><p>Through planned maintenance programs, Rayakonstruksi supports companies in inspecting, cleaning, and repairing critical components that directly impact production performance. Every project is executed under strict <strong>Health, Safety, and Environment (HSE)</strong> standards, supported by experienced professionals.</p>',
                'image'        => 'blog-images/01K80F283ZGJ2V9WZ3AK6FY1J4.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-01-01 03:00:30',
                'created_at'   => '2025-01-01 03:00:30',
                'updated_at'   => '2025-01-01 03:00:30',
                'deleted_at'   => null,
            ],
            [
                'id'           => 14,
                'title'        => 'Understanding Catalyst Loading Operations',
                'slug'         => 'understanding-catalyst-loading-operations-8J7Bd',
                'content'      => '<p>In this episode, we take a closer look at one of the most essential services in industrial construction: <strong>Catalyst Loading</strong>.</p><p>The conversation is light, insightful, and perfect for anyone curious about how the industry continues to innovate and evolve.</p><p>Also watch the full video now on our YouTube channel: <strong>Azure Investama Grup</strong>.</p>',
                'image'        => 'blog-images/01K80FKEM0R2M5935HST1Q3EBE.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-02-13 09:30:56',
                'created_at'   => '2025-02-13 09:30:56',
                'updated_at'   => '2025-02-13 09:30:56',
                'deleted_at'   => null,
            ],
            [
                'id'           => 17,
                'title'        => 'Get to know RAYA',
                'slug'         => 'get-to-know-raya-konstruksi-internasional-0JIfM',
                'content'      => '<p>Get to know <strong>Raya Konstruksi Internasional!</strong></p><p>A construction company committed to delivering innovative and high-quality solutions. Let\'s build the future together.</p><p><strong><em>Raya Konstruksi — Building Tomorrow, Today.</em></strong></p>',
                'image'        => 'blog-images/01K8HTG2Z651F4JGDEMWVC0P42.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-10-16 01:12:19',
                'created_at'   => '2025-10-16 01:12:19',
                'updated_at'   => '2025-10-16 01:12:19',
                'deleted_at'   => null,
            ],
            [
                'id'           => 18,
                'title'        => 'Sumpah Pemuda',
                'slug'         => 'sumpah-pemuda-Mg7IT',
                'content'      => '<p>October 28th, we commemorate <strong>Youth Pledge Day</strong> as a reminder of the courage and unity shown by Indonesia\'s young generation in 1928.</p><p>In the field of construction, young professionals play a vital role as drivers of innovation. RAYA believes that the future of Indonesia\'s infrastructure lies in the hands of dedicated and forward-thinking young talents.</p><p>Through collaboration across generations, we continue strengthening the nation\'s foundation with <strong>character, creativity and unity of purpose</strong>.</p>',
                'image'        => 'blog-images/01K8PTRYBAHJGMAEBRV0FKQS9N.png',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-10-28 01:54:03',
                'created_at'   => '2025-10-28 01:54:03',
                'updated_at'   => '2025-10-28 01:54:03',
                'deleted_at'   => null,
            ],
            [
                'id'           => 19,
                'title'        => 'Plant Maintenance in Sumba Manis',
                'slug'         => 'plant-maintenance-in-sumba-manis-xADZR',
                'content'      => '<p>Managing a sugar production facility is a sustained, high-pressure process. At <strong>Sumba Manis</strong>, one of the developing sugar manufacturing plants in East Indonesia, Raya Konstruksi has supported the plant as a <strong>mechanical fabrication and maintenance vendor</strong>.</p><p>Our scope includes:</p><ul><li>Fabrication of structures</li><li>Scheduled maintenance</li><li>Calibration of industrial rotating machines</li></ul><p>All to avoid unplanned downtime and extend equipment lifespan.</p>',
                'image'        => 'blog-images/01K9RAHACTKAC94JRX4DWZMTG1.webp',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-01-17 02:04:40',
                'created_at'   => '2025-01-17 02:04:40',
                'updated_at'   => '2025-01-17 02:04:40',
                'deleted_at'   => null,
            ],
            [
                'id'           => 20,
                'title'        => 'Apical Works',
                'slug'         => 'apical-works-mHNsz',
                'content'      => '<p>A stronger refinery starts from the ground up. Through advanced <strong>concrete pavement and shotcrete solutions</strong> at Refinery 3 &amp; 4 in Balikpapan, RAYA delivers faster, safer, and longer-lasting civil works engineered for industrial performance.</p><p>As a trusted construction partner for <strong>Kutai Refinery Nusantara of Apical Group</strong>, we ensure trusted performance from the ground up.</p>',
                'image'        => 'blog-images/01K9RVHKN3G0M1QTT0EJEDNK2P.png',
                'user_id'      => 1,
                'is_published' => 0,
                'published_at' => '2025-11-11 06:02:00',
                'created_at'   => '2025-11-11 06:02:00',
                'updated_at'   => '2025-11-11 06:02:00',
                'deleted_at'   => null,
            ],
            [
                'id'           => 21,
                'title'        => 'Concrete Pavement TBM',
                'slug'         => 'concrete-pavement-tbm-uiNBx',
                'content'      => '<p>Starting the day with a <strong>Toolbox Meeting (TBM)</strong> — a moment to align the team, update progress, and reinforce safety awareness on site.</p><p>Today\'s focus:</p><ul><li>Concrete Pavement (Shotcrete Refinery 3 &amp; 4)</li><li>Floor &amp; Wall Repair (Refinery 1, 2, 3 &amp; 5)</li></ul><p><em>Because great work begins with great preparation.</em></p>',
                'image'        => 'blog-images/01KC5MBT2FAW12ENGDACCTTFD1.webp',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-11-11 02:37:49',
                'created_at'   => '2025-11-11 02:37:49',
                'updated_at'   => '2025-11-11 02:37:49',
                'deleted_at'   => null,
            ],
            [
                'id'           => 22,
                'title'        => 'Pray For Sumatra',
                'slug'         => 'pray-for-sumatra-MML9P',
                'content'      => '<p>Our deepest sympathy goes to the communities in Sumatra impacted by the devastating floods and landslides.</p><p>May the response and recovery efforts proceed smoothly, and may Sumatra heal soon. 🤍</p>',
                'image'        => 'blog-images/01KC5NGD2W68KB5MS3RZGWE84T.webp',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-11-29 02:57:47',
                'created_at'   => '2025-11-29 02:57:47',
                'updated_at'   => '2025-11-29 02:57:47',
                'deleted_at'   => null,
            ],
            [
                'id'           => 23,
                'title'        => 'RAYA Maintenance Works',
                'slug'         => 'raya-maintenance-woks-VJlsu',
                'content'      => '<p>Raya Konstruksi supports your <strong>daily and shutdown maintenance</strong> needs. With skilled professionals and full attention to safety, we help your plant run seamlessly without interruptions.</p>',
                'image'        => 'blog-images/01KC5Q0YSKFGGWPWJAK813VA1P.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-12-04 03:24:21',
                'created_at'   => '2025-12-04 03:24:21',
                'updated_at'   => '2025-12-04 03:24:21',
                'deleted_at'   => null,
            ],
            [
                'id'           => 24,
                'title'        => 'RAYA Pipe Fabrication',
                'slug'         => 'raya-pipe-fabrication-i36JE',
                'content'      => '<p><strong>Pipe fabrication</strong> is more than just welding — it\'s a precise, multi-stage process that demands accuracy, skill, and strict quality control.</p><p>From cutting and beveling to fit-up, welding, and final inspection, every detail plays a crucial role in ensuring safety and performance in industrial environments.</p><p>At <strong>Raya Konstruksi</strong>, we execute each step with discipline and engineering-level precision.</p>',
                'image'        => 'blog-images/01KC5QHA66ZZ7Z52Q7JM95AP0P.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-12-10 03:33:16',
                'created_at'   => '2025-12-10 03:33:16',
                'updated_at'   => '2025-12-10 03:33:16',
                'deleted_at'   => null,
            ],
            [
                'id'           => 25,
                'title'        => 'Importance Of Safety Shoes',
                'slug'         => 'importance-of-safety-shoes-8O8O7',
                'content'      => '<p><strong>Safety shoes</strong> aren\'t just part of the uniform — they\'re engineered protection.</p><p>From impact resistance to slip prevention, chemical shielding, and heat protection, every feature is designed to keep workers safe on-site. Even the reflective elements play a crucial role: increasing visibility in low-light areas to reduce accidents.</p><p><em>In construction, safety isn\'t optional. It\'s your first layer of defense.</em></p>',
                'image'        => 'blog-images/01KD4EVFXNGA3A2VWWCS4AB4NC.webp',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-12-18 01:57:37',
                'created_at'   => '2025-12-18 01:57:37',
                'updated_at'   => '2025-12-18 01:57:37',
                'deleted_at'   => null,
            ],
            [
                'id'           => 26,
                'title'        => 'Happy Mother\'s Day',
                'slug'         => 'happy-mothers-day-ZX4Wc',
                'content'      => '<p><strong>Happy Mother\'s Day.</strong> 💐</p><p>Just as strong structures begin with solid foundations — our lives are built on a mother\'s love, care, and resilience.</p>',
                'image'        => 'blog-images/01KD4F98MTPVHWB4FT6SRR0B26.webp',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-12-22 02:05:19',
                'created_at'   => '2025-12-22 02:05:19',
                'updated_at'   => '2025-12-22 02:05:19',
                'deleted_at'   => null,
            ],
            [
                'id'           => 27,
                'title'        => 'YEAR-END MESSAGE',
                'slug'         => 'year-end-message-SFcIV',
                'content'      => '<p>Closing 2025 with <strong>gratitude</strong>. Carrying forward the lessons, hoping for health, ease, and steady progress in the year ahead.</p><p><strong>Merry Christmas and Happy New Year 2026!</strong> 🌟</p>',
                'image'        => 'blog-images/01KDYR32AH9MMBSZ65ZSQXPXJ2.jpg',
                'user_id'      => 1,
                'is_published' => 1,
                'published_at' => '2025-12-31 06:59:54',
                'created_at'   => '2025-12-31 06:59:54',
                'updated_at'   => '2025-12-31 06:59:54',
                'deleted_at'   => null,
            ],
        ];

        // Upsert: insert if not exists, update if ID already exists
        DB::table('blogs')->upsert(
            $blogs,
            ['id'],   // unique key to match on
            ['title', 'slug', 'content', 'image', 'user_id', 'is_published', 'published_at', 'updated_at', 'deleted_at']
        );

        $this->command->info('BlogSeeder: ' . count($blogs) . ' records seeded successfully.');
    }
}
