<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'title'        => 'UOI Turnaround & Maintenance Project',
                'slug'         => 'uoi-turnaround-maintenance',
                'client'       => 'PT Unilever Oleochemical Indonesia',
                'duration'     => 'Nov 2024 – Aug 2025',
                'location'     => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'description'  => 'Turnaround and maintenance project covering mechanical, piping, civil, and electrical works.',
                'image'        => '/assets/img/projects/uoi-1/uoi-1 (1).webp',
                'gallery'      => [
                    '/assets/img/projects/uoi-1/uoi-1 (1).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (2).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (3).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (4).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (5).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (6).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (7).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (8).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (9).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (10).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (11).webp',
                    '/assets/img/projects/uoi-1/uoi-1 (12).webp',
                    '/assets/img/projects/uoi-1/gal-1.jpeg',
                    '/assets/img/projects/uoi-1/gal-2.jpeg',
                ],
            ],
            [
                'title'        => 'Project Management & Construction Sugar Refinery Plant',
                'slug'         => 'msm-sugar-refinery-construction',
                'client'       => 'PT Muria Sumba Manis',
                'duration'     => 'Jan 2020 – Jun 2022',
                'location'     => 'Sumba, NTB',
                'service_type' => 'Fabrication & Construction',
                'description'  => 'Comprehensive project management and construction for sugar refinery plant.',
                'image'        => '/assets/img/projects/msm/cover.webp',
                'gallery'      => [
                    '/assets/img/projects/msm/msm-1.webp',
                    '/assets/img/projects/msm/msm-2.webp',
                    '/assets/img/projects/msm/msm-4.webp',
                    '/assets/img/projects/msm/msm-5.webp',
                    '/assets/img/projects/msm/msm-6.webp',
                    '/assets/img/projects/msm/msm-7.webp',
                    '/assets/img/projects/msm/msm-8.webp',
                    '/assets/img/projects/msm/msm-9.webp',
                    '/assets/img/projects/msm/msm-10.webp',
                    '/assets/img/projects/msm/msm-11.webp',
                    '/assets/img/projects/msm/msm-12.webp',
                    '/assets/img/projects/msm/msm-13.webp',
                    '/assets/img/projects/msm/msm-14.webp',
                    '/assets/img/projects/msm-1/hero.jpeg',
                    '/assets/img/projects/msm-2/hero.jpeg',
                    '/assets/img/projects/msm-2/gal-2.jpeg',
                    '/assets/img/projects/msm-3/hero.jpeg',
                    '/assets/img/projects/msm-3/gal-2.jpeg',
                ],
            ],
            [
                'title'        => 'RDMP RU-V Balikpapan ME-03.4 ISBL Tanks Project',
                'slug'         => 'rdmp-isbl-tanks',
                'client'       => 'Pertamina RU V',
                'duration'     => 'Mar 2024 – Feb 2025',
                'location'     => 'Balikpapan, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'description'  => 'RDMP RU-V Balikpapan ISBL tanks construction project.',
                'image'        => '/assets/img/projects/rdmp/cover.webp',
                'gallery'      => [
                    '/assets/img/projects/rdmp/rdmp-1.webp',
                    '/assets/img/projects/rdmp/rdmp-2.webp',
                    '/assets/img/projects/rdmp/rdmp-3.webp',
                    '/assets/img/projects/rdmp/rdmp-4.webp',
                    '/assets/img/projects/rdmp/rdmp-5.webp',
                    '/assets/img/projects/pertamina-1/hero.jpeg',
                    '/assets/img/projects/pertamina-1/gal-1.png',
                    '/assets/img/projects/pertamina-1/gal-2.jpeg',
                    '/assets/img/projects/rdmp-032/hero.jpeg',
                    '/assets/img/projects/rdmp-034/hero.jpeg',
                    '/assets/img/projects/rdmp-034/gal-1.jpeg',
                ],
            ],
            [
                'title'        => 'LINE Ethylene Plant Construction Project',
                'slug'         => 'line-ethylene-lotte-chemical',
                'client'       => 'PT Lotte Chemical Indonesia',
                'duration'     => 'Jan 2023 – Nov 2024',
                'location'     => 'Cilegon, Banten',
                'service_type' => 'Fabrication & Construction',
                'description'  => 'Structure, mechanical, and piping construction for LINE Ethylene Plant.',
                'image'        => '/assets/img/projects/lotte/cover.webp',
                'gallery'      => [
                    '/assets/img/projects/lotte/lotte-1.webp',
                    '/assets/img/projects/lotte/lotte-2.webp',
                    '/assets/img/projects/lotte/lotte-3.webp',
                    '/assets/img/projects/lotte/lotte-4.webp',
                    '/assets/img/projects/lotte/lotte-5.webp',
                    '/assets/img/projects/lotte/lotte-6.webp',
                    '/assets/img/projects/line-1/hero.jpeg',
                    '/assets/img/projects/line-2/hero.jpeg',
                    '/assets/img/projects/line-2/gal-1.jpg',
                    '/assets/img/projects/line-3/hero.jpeg',
                    '/assets/img/projects/line-3/gal-1.jpg',
                    '/assets/img/projects/lotte-mps/lotte-mps (3).webp',
                ],
            ],
            [
                'title'        => 'Air Products SMIP Mechanical & Piping',
                'slug'         => 'air-products-smip',
                'client'       => 'PT Air Products Indonesia Gases',
                'duration'     => 'Oct 2023 – Jun 2025',
                'location'     => 'Sei Mangkei, Sumut',
                'service_type' => 'Fabrication & Construction',
                'description'  => 'Mechanical and piping construction and installation for Air Products SMIP project.',
                'image'        => '/assets/img/projects/airproduct/cover-1.webp',
                'gallery'      => [
                    '/assets/img/projects/airproduct/cover-1.webp',
                    '/assets/img/projects/ap-1/hero.jpeg',
                    '/assets/img/projects/ap-1/gal-1.png',
                    '/assets/img/projects/ap-2/hero.jpeg',
                    '/assets/img/projects/ap-2/gal-1.jpg',
                    '/assets/img/projects/ap-2/gal-2.png',
                    '/assets/img/projects/ap-3/hero.jpeg',
                    '/assets/img/projects/ap-3/gal-1.png',
                    '/assets/img/projects/ap-3/gal-2.jpeg',
                    '/assets/img/projects/ap-4/hero.jpeg',
                ],
            ],
            [
                'title'        => 'Catalyst Handling Lotte Chemical',
                'slug'         => 'catalyst-handling-lotte',
                'client'       => 'PT Lotte Chemical Indonesia',
                'duration'     => 'Nov 2024 – Dec 2024',
                'location'     => 'Cilegon, Banten',
                'service_type' => 'Catalyst Handling',
                'description'  => 'Professional catalyst loading and handling for GHU I, II and Clay Towers at LINE Ethylene Plant.',
                'image'        => '/assets/img/projects/lotte-catalyst/catalyst-3.webp',
                'gallery'      => [
                    '/assets/img/projects/lotte-catalyst/catalyst (1).webp',
                    '/assets/img/projects/lotte-catalyst/catalyst (2).webp',
                    '/assets/img/projects/lotte-catalyst/catalyst (4).webp',
                    '/assets/img/projects/lotte-catalyst/catalyst (5).webp',
                    '/assets/img/projects/lotte-catalyst/catalyst-3.webp',
                ],
            ],
            [
                'title'        => 'Akatara Commissioning Support',
                'slug'         => 'akatara-commissioning',
                'client'       => 'Jadestone Energy Lemang, Pte., Ltd.',
                'duration'     => 'Mar 2024 – Aug 2024',
                'location'     => 'Jambi, Indonesia',
                'service_type' => 'Operation & Maintenance',
                'description'  => 'Commissioning support and manpower supply for Akatara gas project.',
                'image'        => '/assets/img/projects/akatara/cover.webp',
                'gallery'      => [
                    '/assets/img/projects/akatara/akatara (1).webp',
                    '/assets/img/projects/akatara/akatara (2).webp',
                    '/assets/img/projects/akatara/akatara (3).webp',
                    '/assets/img/projects/akatara/akatara (4).webp',
                    '/assets/img/projects/akatara-1/cover-1.jpg',
                    '/assets/img/projects/akatara-1/akatara (1).jpg',
                    '/assets/img/projects/akatara-1/akatara (2).jpg',
                    '/assets/img/projects/akatara-1/akatara (3).jpg',
                    '/assets/img/projects/akatara-1/akatara (4).jpg',
                    '/assets/img/projects/akatara-1/gal-2.jpeg',
                ],
            ],
            [
                'title'        => 'Enerco Civil & Construction Works',
                'slug'         => 'enerco-civil-construction',
                'client'       => 'Enerco',
                'duration'     => '2023 – 2024',
                'location'     => 'Indonesia',
                'service_type' => 'Civil & Road Works',
                'description'  => 'Civil and construction works project for Enerco.',
                'image'        => '/assets/img/projects/enerco-1/enerco-1.webp',
                'gallery'      => [
                    '/assets/img/projects/enerco-1/enerco-1.webp',
                    '/assets/img/projects/enerco-1/enerco-2.webp',
                    '/assets/img/projects/enerco-1/enerco-3.webp',
                    '/assets/img/projects/enerco-1/enerco-4.webp',
                    '/assets/img/projects/enerco-1/enerco-5.webp',
                    '/assets/img/projects/enerco-1/gal-1.jpeg',
                    '/assets/img/projects/enerco-2/gal-1.jpeg',
                    '/assets/img/projects/enerco-2/gal-2.jpeg',
                    '/assets/img/projects/enerco-3/hero.jpeg',
                    '/assets/img/projects/enerco-3/enerco-2.jpg',
                    '/assets/img/projects/enerco-3/enerco-3.jpg',
                    '/assets/img/projects/enerco-3/enerco-4.jpg',
                    '/assets/img/projects/enerco-3/enerco-5.jpg',
                ],
            ],
            [
                'title'        => 'ISS (Indo Sutech) Project',
                'slug'         => 'indo-sutech-project',
                'client'       => 'ISS (Indo Sutech Sejahtera)',
                'duration'     => 'Sep 2026',
                'location'     => 'Indonesia',
                'service_type' => 'Operation & Maintenance',
                'description'  => 'Construction and maintenance works for Indo Sutech Sejahtera.',
                'image'        => '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.44.jpeg',
                'gallery'      => [
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.44.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.44 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.45.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.45 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.45 (2).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.46.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.46 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.47.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.47 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.47 (2).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.48.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.48 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.48 (2).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.49.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.49 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.49 (2).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.50.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.50 (1).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.50 (2).jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.51.jpeg',
                    '/assets/img/projects/sutech/WhatsApp Image 2026-09-25 at 13.57.5456.jpeg',
                ],
            ],
            [
                'title'        => 'Tangguh Project',
                'slug'         => 'tangguh-project',
                'client'       => 'Tangguh',
                'duration'     => '2025',
                'location'     => 'Papua',
                'service_type' => 'Operation & Maintenance',
                'description'  => 'Construction and maintenance works for Tangguh project.',
                'image'        => '/assets/img/projects/tangguh-1/hero.jpeg',
                'gallery'      => [
                    '/assets/img/projects/tangguh-1/hero.jpeg',
                    '/assets/img/projects/tangguh-1/gal-1.jpeg',
                ],
            ],
            [
                'title'        => 'Road Maintenance Package',
                'slug'         => 'halmahera-road-maintenance',
                'client'       => 'Halmahera Sukses Mineral',
                'duration'     => 'Jun 2023 – May 2025',
                'location'     => 'Halmahera',
                'service_type' => 'Civil & Road Works',
                'description'  => 'Road maintenance package for mining operations in Halmahera.',
                'image'        => '/assets/img/projects/header-msm-1.webp',
                'gallery'      => [],
            ],
            [
                'title'        => 'Construction Work Pesona Hutan Asraya',
                'slug'         => 'asraya-housing-development',
                'client'       => 'PT Casa Asraya Properti',
                'duration'     => 'Jul 2025 – Apr 2026',
                'location'     => 'Pekanbaru, Riau',
                'service_type' => 'Civil & Road Works',
                'description'  => 'Construction of housing development Pesona Hutan Asraya.',
                'image'        => '/assets/img/projects/construction-1.webp',
                'gallery'      => [],
            ],
        ];

        foreach ($projects as $data) {
            Project::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
