<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            // FABRICATION & CONSTRUCTION
            [
                'title' => 'Project Management & Construction Sugar Refinery Plant',
                'client' => 'PT Muria Sumba Manis',
                'duration' => 'Jan 2020 - Jun 2022',
                'location' => 'Sumba, NTB',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Piping Process Area Sugar Refinery Plant',
                'client' => 'PT Muria Sumba Manis',
                'duration' => 'Jan 2020 - Jun 2022',
                'location' => 'Sumba, NTB',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'RDMP RU-V Balikpapan ME-03.4 ISBL Tanks Project',
                'client' => 'Pertamina RU V',
                'duration' => 'Mar 2024 - Feb 2025',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'RDMP RU-V Balikpapan ME-03.2 OSBL Tanks Project',
                'client' => 'Pertamina RU V',
                'duration' => 'Mar 2022 - Dec 2023',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'RDMP RU-V Balikpapan Turn Around - Piping, Insulation & Painting for Carbon Steel Piping System in HCC Area',
                'client' => 'Pertamina RU V',
                'duration' => 'Jul 2022 - Aug 2022',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'LINE Ethylene Plant Structure, Mechanical, Piping Construction Project',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Jan 2023 - Nov 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Piping LINE WP3 BTX',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Apr 2023 - Mar 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Mechanical & Piping Construction Work 2XPHG830 Project',
                'client' => 'PT Air Products Indonesia Gases',
                'duration' => 'Oct 2023 - Jun 2024',
                'location' => 'Sangkulirang, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Mechanical & Piping Construction Work 1 x PHG830 + 2 x PSA64-SOG',
                'client' => 'PT Air Products Indonesia Gases',
                'duration' => 'Jan 2023 - Jul 2023',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Mechanical & Piping Installation Offsite SMIP SMR +40 HPN-SOG',
                'client' => 'PT Air Products Indonesia Gases',
                'duration' => 'Oct 2024 - Jun 2025',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Mechanical & Piping Installation Offsite SMIP SMR +40 HPN-SOG Additional',
                'client' => 'PT Air Products Indonesia Gases',
                'duration' => 'Mar 2025 - Jun 2025',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'OKI1 Tissue – MEIA Installation Of 1 Set Rewinder',
                'client' => 'OKI Pulp & Paper',
                'duration' => 'Apr 2026 – Jul 2026',
                'location' => 'Palembang, Sumsel',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],
            [
                'title' => 'Roofing Siding Installation and Piping Works',
                'client' => 'Apical',
                'duration' => 'Mar 2026 – Jun 2026',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Fabrication & Construction',
                'image' => null,
            ],

            // OPERATION, MAINTENANCE & CATALYST HANDLING
            [
                'title' => 'Change Out Catalyst ARHDM Train 13',
                'client' => 'PT KPI RU VI',
                'duration' => 'Apr 2023 - May 2023',
                'location' => 'Balongan, Jabar',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Manpower Supply LINE WP3 BTX',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Feb 2023 - Nov 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Heavy Equipment Supply LINE WP3 BTX',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Feb 2023 - Nov 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Scaffolding Supply LINE WP3 BTX',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Mar 2023 - Nov 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Operation & Maintenance Sugar Refinery Plant',
                'client' => 'PT Muria Sumba Manis',
                'duration' => 'Apr 2022 - Apr 2024',
                'location' => 'Sumba, NTB',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Commissioning Support Manpower Supply Akatara Project',
                'client' => 'Jadestone Energy Lemang, Pte., Ltd.',
                'duration' => 'Mar 2024 - Aug 2024',
                'location' => 'Jambi, Indonesia',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Unloading & Loading Furnace',
                'client' => 'PT KPI RU II',
                'duration' => 'Jun 2024 - Jul 2024',
                'location' => 'Dumai, Riau',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Unload Adsorbent Pressure Swing Adsorbent (COA PSA) 22- V-109 K, L & M',
                'client' => 'PT KPI RU VI',
                'duration' => 'Jul 2024 - Aug 2024',
                'location' => 'Balongan, Jabar',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Change Out Catalyst 37-R-101B Unit POC',
                'client' => 'PT KPI RU VI',
                'duration' => 'Sep 2024 - Oct 2024',
                'location' => 'Balongan, Jabar',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Vacuum Machine Supply',
                'client' => 'PT KPI RU VI',
                'duration' => 'Nov 2024 - Dec 2024',
                'location' => 'Balongan, Jabar',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'LINE Ethyelene Plant GHU I, II & Clay Towers Catalyst Loading',
                'client' => 'PT Lotte Chemical Indonesia',
                'duration' => 'Nov 2024 - Dec 2024',
                'location' => 'Cilegon, Banten',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Turn Around Maintenance',
                'client' => 'PT Unilever Oleochemical Indonesia',
                'duration' => 'Nov 2024 - Dec 2024',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'SMR Reactors & Adsorbers Catalyst Loading',
                'client' => 'PT Air Products Indonesia Gases',
                'duration' => 'Mar 2025 - Apr 2025',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Catalyst Handling',
                'image' => null,
            ],
            [
                'title' => 'Welder Team for Rectify Process Drain Line in FA2',
                'client' => 'PT Unilever Oleochemical Indonesia',
                'duration' => 'Sep 2025 - Oct 2025',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Repair Floor & Wall Refinery',
                'client' => 'PT Kutai Refinery Nusantara',
                'duration' => 'Sep 2025 - Oct 2025',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Quality Office Roof Leak Repair',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Galvanized Pipe Replacement (Raw Water KINRA to GWT)',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Sluice Gate Repair (Gate A & B) - Service',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'New Soak Pit for Toilet Gate C',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Pocket Drain Medium & High Pressure Steam Utility',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'New Bund Wall in Soap 2',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Tapping Point Material for Project #3',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Biomass Storage New Stormwater Drainage (West Side)',
                'client' => 'Unilever Oleochemical Indonesia',
                'duration' => 'Dec 2025 - Present',
                'location' => 'Sei Mangkei, Sumut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Repair Floor and Wall Refinery 1, 2, 3 & 5',
                'client' => 'Kutai Refinery Nusantara (Apical - RGE)',
                'duration' => 'Oct 2025 - Apr 2026',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Repair Room Mess D',
                'client' => 'Kutai Refinery Nusantara (Apical - RGE)',
                'duration' => 'Oct 2025 - Apr 2026',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Meeting Room and Gutter Repairing',
                'client' => 'Kutai Refinery Nusantara (Apical - RGE)',
                'duration' => 'Oct 2025 - Apr 2026',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Concrete Pavement at Sortcrete Refinery 3 and 4',
                'client' => 'Kutai Refinery Nusantara (Apical - RGE)',
                'duration' => 'Oct 2025 - Apr 2026',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Cleaning & Repair Sand Filter Tank Demin',
                'client' => 'Sari Dumai Oleo (Apical - RGE)',
                'duration' => 'Dec 2025 – Dec 2025',
                'location' => 'Marunda, Jakut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'MC. Dermott Project - Construction Services Agreement',
                'client' => 'Tatamulia Nusantara Indah',
                'duration' => 'Jan 2026 – Apr 2026',
                'location' => 'Batam',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Service Work for Troubleshoot and Overhaul of Low Pressure CO2 Storage Tank System',
                'client' => 'Cirebon Energi Prasarana (Cirebon Power)',
                'duration' => 'Apr 2026 - Oct 2026',
                'location' => 'Cirebon',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Mochtar Prabu Maintenance Package',
                'client' => 'Pupuk Indonesia Logistik (PIHC)',
                'duration' => 'Jan 2026 - Present',
                'location' => 'Palembang, Sumsel',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Roofing Replacement for WTP #3',
                'client' => 'Kutai Refinery Nusantara (Apical - RGE Group)',
                'duration' => 'Feb 2026 - Present',
                'location' => 'Balikpapan, Kaltim',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Fabrication & Installation Air Compressor',
                'client' => 'Asianagro Agungjaya (Apical - RGE Group)',
                'duration' => 'Feb 2026 - Present',
                'location' => 'Marunda, Jakut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Manpower Supply for Electrical Works',
                'client' => 'Asianagro Agungjaya (Apical - RGE Group)',
                'duration' => 'Feb 2026 - Present',
                'location' => 'Marunda, Jakut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],
            [
                'title' => 'Tie In Air Compressor, Chiller, Condensor, Cooling Tower',
                'client' => 'PT Asianagro Agung Jaya – Apical Marunda',
                'duration' => 'Mar 2026 - Present',
                'location' => 'Marunda, Jakut',
                'service_type' => 'Operation & Maintenance',
                'image' => null,
            ],

            // CIVIL WORKS
            [
                'title' => 'Road Maintenance Package',
                'client' => 'Halmahera Sukses Mineral',
                'duration' => 'Jun 2023 - May 2025',
                'location' => 'Halmahera',
                'service_type' => 'Civil & Road Works',
                'image' => null,
            ],
            [
                'title' => 'Road Construction Package',
                'client' => 'Bukit Asam',
                'duration' => 'Dec 2024 - Aug 2025',
                'location' => 'Sumsel',
                'service_type' => 'Civil & Road Works',
                'image' => null,
            ],
            [
                'title' => 'Construction Work of the Pesona Hutan Asraya Housing Development',
                'client' => 'PT Casa Asraya Properti',
                'duration' => 'Jul 2025 - Apr 2026',
                'location' => 'Pekanbaru, Riau',
                'service_type' => 'Civil & Road Works',
                'image' => null,
            ],
            [
                'title' => 'Fencing Fabrication & Installation',
                'client' => 'OKI Pulp & Paper',
                'duration' => 'May 2026 – Nov 2026',
                'location' => 'Palembang, Sumsel',
                'service_type' => 'Civil & Road Works',
                'image' => null,
            ],
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}

