<?php

/**
 * @see https://github.com/artesaos/seotools
 */

return [
    'meta' => [
        /*
         * The default configurations to be used by the meta generator.
         */
        'defaults'       => [
            'title'        => "Makadia Group International", // set false to total remove
            'titleBefore'  => false, // Put defaults.title before page title, like 'It's Over 9000! - Dashboard'
            'description'  => 'Makadia Group menyediakan layanan Catalyst Loading dan Catalyst Handling yang aman, efisien, dan sesuai standar industri. Dengan tim berpengalaman dan teknologi terkini, kami memastikan optimalisasi proses, penggantian katalis, dan manajemen keselamatan untuk industri petrokimia dan energi', // set false to total remove
            'separator'    => ' - ',
            'keywords'     => [
                "Catalyst Loading Indonesia",
                "Catalyst Loading Pulau Jawa",
                "Catalyst Loading Pulau Sumatera",
                "Catalyst Loading Pulau Kalimantan",
                "Catalyst Loading Pulau Sulawesi",
                "Catalyst Handling Indonesia",
                "Catalyst Handling Pulau Jawa",
                "Catalyst Handling Pulau Sumatera",
                "Catalyst Handling Pulau Kalimantan",
                "Catalyst Handling Pulau Sulawesi",
                "Catalyst Handling Services",
                "Safe Catalyst Loading Solutions",
                "Catalyst Handling Experts",
                "Industrial Catalyst Loading",
                "Catalyst Changeout Services",
                "Catalyst Management Professionals",
                "On-Site Catalyst Handling",
                "Catalyst Handling and Maintenance",
                "Catalyst Replacement Solutions",
                "Catalyst Activation Services",
                "Reliable Catalyst Handling Teams",
                "Catalyst Inspection and Safety",
                "Catalyst Maintenance Support",
                "Catalyst Unloading Services",
                "Catalyst Loading for Petrochemical Plants",
                "Catalyst Optimization and Activation",
                "Industrial Catalyst Replacement Experts",
                "Catalyst Safety Training Programs",
                "Catalyst Deployment and Handling",
                "Catalyst Turnaround Solutions",
                "Catalyst Handling Contractors",
                "Catalyst Loading Safety Experts",
                "Catalyst Efficiency Management",
                "Advanced Catalyst Handling Services",
                "Catalyst Change Management Consultants",
                "Emergency Catalyst Replacement Teams",
                "Catalyst Process Optimization",
                "Catalyst Preparation Services",
                "Catalyst Lifecycle Maintenance",
                "Catalyst Storage and Handling Services",
                "Catalyst Handling for Energy Plants",
                "Catalyst Handling and Safety Practices",
                "Catalyst Activation for Chemical Plants",
                "Catalyst Changeout for Refinery Operations",
                "Catalyst Handling for Industrial Plants",
                "Catalyst Handling in Hazardous Environments",
                "Catalyst Maintenance and Disposal Experts",
                "Catalyst Handling Equipment Solutions",
                "Catalyst Loading Innovations",
                "Catalyst Inspection and Loading Professionals",
                "Catalyst Maintenance Specialists",
                "Catalyst Loading for Refinery Efficiency",
                "Catalyst Handling for Oil and Gas",
                "Catalyst Troubleshooting Services",
                "Catalyst Replacement for Optimal Performance",
                "Catalyst Handling Techniques",
                "Catalyst Handling Safety Compliance",
                "Catalyst Operations and Monitoring",
                "Catalyst Handling in Chemical Processing",
                "Catalyst Disposal and Recycling",
                "Catalyst Reactivation Services",
                "Catalyst Maintenance Planning",
                "Catalyst Optimization Strategies",
                "Catalyst Replacement and Inspection",
                "Catalyst Handling for Sustainable Operations",
                "Catalyst Turnaround Management",
                "Catalyst Safety and Compliance Experts",
                "Catalyst Preparation and Activation",
                "Catalyst Deployment for Petrochemicals",
                "Catalyst Unloading for Refinery Turnaround",
                "Catalyst Handling Logistics",
                "Catalyst Storage Solutions",
                "Catalyst Loading Efficiency Practices",
                "Catalyst Operational Safety",
                "Catalyst Change Services for Industrial Plants",
                "Catalyst Handling for High-Risk Areas",
                "Catalyst Maintenance Technicians",
                "Catalyst Activation for Performance Improvement",
                "Catalyst Optimization for Industrial Use",
                "Catalyst Disposal Solutions",
                "Catalyst Safe Handling Practices",
                "Catalyst Turnaround Projects",
                "Catalyst Troubleshooting and Repair",
                "Catalyst Maintenance Teams",
                "Catalyst Monitoring and Support Services",
                "Catalyst Deployment Experts",
                "Catalyst Handling and Monitoring",
                "Catalyst Safety Inspection Services",
                "Catalyst Replacement Experts",
                "Catalyst Troubleshooting and Monitoring",
                "Catalyst Lifecycle Support",
                "Catalyst Maintenance for Energy Plants",
                "Catalyst Activation for Refinery Efficiency",
                "Catalyst Handling for Petrochemical Plants",
                "Catalyst Optimization for Safety",
                "Catalyst Equipment Handling",
                "Catalyst Preparation for Operations",
                "Catalyst Disposal for Chemical Plants",
                "Catalyst Storage and Activation",
                "Catalyst Safe Disposal Practices",
                "Catalyst Handling Projects",
                "Catalyst Monitoring Systems",
                "Catalyst Deployment and Optimization",
                "Catalyst Lifecycle Services",
                "Catalyst Handling Innovations",
                "Catalyst Optimization Practices",
                "Catalyst Troubleshooting for Operations",
                "Catalyst Maintenance for Chemical Plants",
                "Catalyst Efficiency Experts",
                "Catalyst Preparation for Petrochemicals",
                "Catalyst Lifecycle Monitoring",
                "Catalyst Activation for High Performance",
                "Catalyst Storage and Maintenance",
                "Catalyst Handling Systems",
                "Catalyst Maintenance and Activation",
                "Catalyst Optimization for Energy Efficiency",
                "Catalyst Turnaround Planning",
                "Catalyst Deployment for Chemical Plants",
                "Catalyst Equipment Maintenance",
                "Catalyst Handling for Operations",
                "Catalyst Handling Optimization Services",
                "Catalyst Maintenance Best Practices",
                "Catalyst Troubleshooting Experts",
                "Catalyst Storage and Loading Experts",
                "Catalyst Handling Support Teams",
                "Catalyst Activation Planning",
                "Catalyst Maintenance for Safety Compliance",
                "Catalyst Deployment Planning",
                "Catalyst Optimization for Refinery Operations",
                "Catalyst Handling for Sustainable Operations",
                "Catalyst Troubleshooting Techniques",
                "Catalyst Maintenance Services",
                "Catalyst Activation Teams",
                "Catalyst Maintenance Innovations",
                "Catalyst Equipment Solutions",
                "Catalyst Handling for Large Projects",
                "Catalyst Lifecycle Management Services",
                "Catalyst Activation for Chemical Efficiency",
                "Catalyst Storage and Handling Professionals",
                "Catalyst Preparation for Safe Operations",
                "Catalyst Handling for High Efficiency",
                "Catalyst Troubleshooting Planning",
                "Catalyst Optimization Teams",
                "Catalyst Handling Maintenance Professionals",
                "Catalyst Equipment Handling Innovations",
                "Catalyst Troubleshooting for Energy Plants",
                "Catalyst Activation for Energy Safety",
                "Catalyst Storage and Deployment Professionals",
                "Catalyst Preparation and Handling Services",
                "Catalyst Efficiency Solutions",
                "Catalyst Storage Maintenance Professionals",
                "Catalyst Lifecycle Optimization",
    
                "Steel Structure Fabrication Experts",
                "Industrial Piping Services",
                "Mechanical Construction Professionals",
                "Structural Steel Solutions",
                "Piping Design and Installation",
                "Customized Steel Fabrication",
                "Heavy Steel Structure Projects",
                "Precision Mechanical Contractors",
                "Welding and Steel Assembly",
                "Industrial Steel Framework",
                "Advanced Piping Technology",
                "Steel and Mechanical Solutions",
                "Industrial Mechanical Systems",
                "Piping for Chemical Plants",
                "High-Performance Mechanical Construction",
                "Steel Structure Contractors",
                "Industrial Piping Fabrication",
                "Steel Framework Installation",
                "Mechanical Systems Design",
                "Piping Contractors for Petrochemicals",
                "Steel Structure Assembly Experts",
                "Mechanical Maintenance Solutions",
                "Precision Welding Contractors",
                "Structural Engineering Solutions",
                "Steel Structure Maintenance",
                "Piping Optimization Services",
                "Mechanical Equipment Installation",
                "Industrial Steel Assembly",
                "Piping Solutions for Refineries",
                "Structural Solutions for Industrial Plants",
                "Heavy-Duty Piping Installation",
                "Industrial Steel Design",
                "Mechanical Construction for Energy Plants",
                "Steel Structure Repair Experts",
                "Industrial Piping Optimization",
                "Steel Assembly Contractors",
                "High-Precision Mechanical Services",
                "Welding Solutions for Industrial Projects",
                "Structural Steel Safety Standards",
                "Piping Installation for Chemical Processing",
                "Customized Mechanical Systems",
                "Structural Fabrication Services",
                "Piping Solutions for High-Performance Plants",
                "Mechanical Installation for Refineries",
                "Steel Structure Innovations",
                "Industrial Steel Repairs",
                "Mechanical Design Experts",
                "Piping Assembly for Oil and Gas",
                "Heavy Steel Construction Solutions",
                "Precision Piping Systems",
                "Structural Contractors for Energy Plants",
                "Steel Assembly Solutions",
                "Industrial Piping Specialists",
                "Steel Framework Experts",
                "Piping Solutions for Hazardous Areas",
                "Advanced Mechanical Fabrication",
                "Welding Specialists for Structural Steel",
                "Industrial Mechanical Design Services",
                "Steel Structure Engineers",
                "Customized Piping Installations",
                "Mechanical Maintenance Professionals",
                "Steel Assembly for Refineries",
                "Industrial Piping and Maintenance",
                "High-Performance Steel Construction",
                "Structural Maintenance Teams",
                "Steel Structure Repair Professionals",
                "Industrial Piping Planning",
                "Piping Maintenance and Repairs",
                "Structural Steel Innovations",
                "Welding Contractors for Large Projects",
                "Mechanical Optimization Solutions",
                "Piping Design and Repairs",
                "Steel Maintenance Solutions",
                "Industrial Mechanical Safety Standards",
                "Structural Solutions for Chemical Plants",
                "Steel Installation for Energy Efficiency",
                "Piping Equipment Experts",
                "Mechanical Systems for Petrochemicals",
                "Heavy-Duty Steel Solutions",
                "Precision Piping Equipment",
                "Structural Engineering for Large Projects",
                "Steel Repairs and Maintenance",
                "Industrial Mechanical Systems Optimization",
                "Steel Structure Innovations for Efficiency",
                "Piping Fabrication and Installation Experts",
    
    
                "Reliable Manpower Supply Services",
                "Professional Scaffolding Solutions",
                "Industrial Equipment Rental Experts",
                "On-Demand Workforce Solutions",
                "Scaffolding for Construction Projects",
                "Heavy Equipment Rental Specialists",
                "Certified Manpower Providers",
                "Temporary Workforce Solutions",
                "Scaffolding Installation Experts",
                "Industrial Rental Services",
                "Skilled Labor Supply",
                "Custom Scaffolding Rentals",
                "Equipment Rental for Industrial Use",
                "Scaffolding for Hazardous Environments",
                "Industrial Workforce Planning",
                "Reliable Equipment Rental Services",
                "Scaffolding Maintenance Experts",
                "Workforce Solutions for Large Projects",
                "Temporary Labor Supply Teams",
                "Industrial Equipment Specialists",
                "Scaffolding for Refineries",
                "Equipment Rental for Petrochemicals",
                "Professional Workforce Providers",
                "Scaffolding Services for Energy Plants",
                "Heavy-Duty Equipment Rentals",
                "Skilled Workforce Contractors",
                "Scaffolding Safety Standards",
                "Reliable Scaffolding Rentals",
                "Equipment Rental for Refineries",
                "Workforce Planning Experts",
                "Industrial Equipment Rentals",
                "Temporary Manpower Solutions",
                "Certified Scaffolding Contractors",
                "Industrial Scaffolding Services",
                "Equipment Rental for Energy Projects",
                "Temporary Workforce for Industrial Plants",
                "Reliable Scaffolding Providers",
                "Certified Equipment Rentals",
                "Workforce Supply for Chemical Plants",
                "Scaffolding Installation for Safety",
                "Equipment Rentals for High-Risk Areas",
                "Skilled Labor for Petrochemicals",
                "Industrial Equipment Supply Services",
                "Workforce Optimization Solutions",
                "Reliable Industrial Workforce",
                "Custom Equipment Rentals",
                "Certified Workforce Supply Services",
                "Skilled Labor Solutions for Industry",
    
                "Industrial Project Management Experts",
                "Project Consultancy Services",
                "Turnkey Project Solutions",
                "Strategic Project Planning Consultants",
                "Industrial Operations Consulting",
                "Risk Management for Projects",
                "End-to-End Project Consulting",
                "Efficient Project Execution Planning",
                "Cost Optimization Consultants",
                "Industrial Project Strategy Experts",
                "Project Execution Teams",
                "Planning Consultants for Large Projects",
                "Risk Management and Compliance",
                "Industrial Strategy Planning",
                "End-to-End Execution Experts",
                "Cost Management Solutions for Projects",
                "Industrial Planning Consultants",
                "Turnkey Operations Planning",
                "Project Optimization Teams",
                "Execution and Planning Experts",
                "Industrial Project Execution Planning",
                "Risk and Cost Management Solutions"
    
            ],
            'canonical'    => false, // Set to null or 'full' to use Url::full(), set to 'current' to use Url::current(), set false to total remove
            'robots'       => false, // Set to 'all', 'none' or any combination of index/noindex and follow/nofollow
        ],
        /*
         * Webmaster tags are always added.
         */
        'webmaster_tags' => [
            'google'    => null,
            'bing'      => null,
            'alexa'     => null,
            'pinterest' => null,
            'yandex'    => null,
            'norton'    => null,
        ],

        'add_notranslate_class' => false,
    ],
    'opengraph' => [
        /*
         * The default configurations to be used by the opengraph generator.
         */
        'defaults' => [
            'title'       => false, //'Over 9000 Thousand!', // set false to total remove
            'description' => false, //'For those who helped create the Genki Dama', // set false to total remove
            'url'         => false, // Set null for using Url::current(), set false to total remove
            'type'        => false,
            'site_name'   => false,
            'images'      => [],
        ],
    ],
    'twitter' => [
        /*
         * The default values to be used by the twitter cards generator.
         */
        'defaults' => [
            //'card'        => 'summary',
            //'site'        => '@LuizVinicius73',
        ],
    ],
    'json-ld' => [
        /*
         * The default configurations to be used by the json-ld generator.
         */
        'defaults' => [
            'title'       => false, //'Over 9000 Thousand!', // set false to total remove
            'description' => false, //'For those who helped create the Genki Dama', // set false to total remove
            'url'         => false, // Set to null or 'full' to use Url::full(), set to 'current' to use Url::current(), set false to total remove
            'type'        => 'WebPage',
            'images'      => [],
        ],
    ],
];
